extends Node

const RIGHT: String = "Right"
const RIGHT_SHAREHOLDING: String = "Shareholding"
const RIGHT_PRIVATE: String = "Private"
const RIGHT_MERITOCRACY: String = "Meritocracy"
const RIGHT_BUSINESS: String = "Business"
const RIGHT_MIGRATION: String = "Migration"
const RIGHT_ELITE: String = "Elite"
const RIGHT_TRADITION: String = "Tradition"
const RIGHT_SECURITY: String = "Security"
const RIGHT_IDENTITY: String = "Identity"

const NEUTRAL_DEMOCRATY: String = "Democraty"
const NEUTRAL_BUDGET: String = "Budget"
const NEUTRAL_JUSTICE: String = "Justice"
const NEUTRAL_CAPITALISM: String = "Capitalism"
const NEUTRAL_INVASION: String = "Invasion"
const NEUTRAL_STATE: String = "State"
const NEUTRAL_LAYOFF: String = "Layoff"
const NEUTRAL_REFORM: String = "Reform"
const NEUTRAL_ELECTION: String = "Election"
const NEUTRAL_LAW: String = "Law"

const LEFT: String = "Left"
const LEFT_ECOLOGY: String = "Ecology"
const LEFT_SOCIAL: String = "Social"
const LEFT_PUBLIC: String = "Public"
const LEFT_PEOPLE: String = "People"
const LEFT_SOCIALISM: String = "Socialism"
const LEFT_SOLIDARITY: String = "Solidarity"
const LEFT_PROGRESSIVISM: String = "Progressivism"
const LEFT_INCLUSIVENESS: String = "Inclusiveness"
const LEFT_STRIKE: String = "Strike"
